version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./frontend/dockerfile
    volumes:
    - .:/home/node/app
    - /home/node/app/node_modules
    ports:
      - "3001:3000"
    env_file:
      - ./frontend/.env
    networks:
      - app-network
    depends_on:
      - pg
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: ./backend/dockerfile
    ports:
      - "3331:3333"
    env_file:
      - ./backend/.env
    networks:
      - app-network
  postgres_db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: baseproject
    ports:
      - "5469:5432"
    networks:
      - app-network
    volumes:
      - database_data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge

volumes:
  database_data:
    driver: local

