version: "3.9"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3003:3003"
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3333:3333"
    depends_on:
      - db
  db:
    container_name: db
    build: ./db
    ports:
      - "5469:5469"