version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./frontend/dockerfile
    volumes:
    - .:/home/node/app
    - /home/node/app/node_modules
    ports:
      - "3001:3000"
    env_file:
      - ./frontend/.env
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: ./backend/dockerfile
    ports:
      - "3331:3333"
    env_file:
      - ./backend/.env